### ISSUE TITLE
关于Tooltip延时的问题

### ISSUE THREAD

**Issue by GSCmax** [hank9999/K5_Tools#10]
现在的Tooltip延时是100ms，这太快了，会造成组件工作不稳定。Windows原生控件（WinForm、WPF等）的Tooltip等待延时默认值都在500ms左右，Windows系统应用更是达到了1000ms以上。还请调大此项数值到500ms以上以求稳定。

**Comment by hank9999** [comment]
500ms 会不会有点太慢了 目前看着还好

**Comment by GSCmax** [comment]
500ms不慢的，Tooltip本意就是要在控件上停留一段时间再触发，基本上提供原生Tooltip支持的语言都都在500ms左右，几乎是规范了。

**Comment by hank9999** [comment]
> 500ms不慢的，Tooltip本意就是要在控件上停留一段时间再触发，基本上提供原生Tooltip支持的语言都都在500ms左右，几乎是规范了。

感觉用户基本上不会停这么久

**Comment by GSCmax** [comment]
它的设计意图不是鼠标放在上面立刻触发的，等待的时间也是在确认用户是否需要阅读提示。

**Comment by hank9999** [comment]
> 它的设计意图不是鼠标放在上面立刻触发的，等待的时间也是在确认用户是否需要阅读提示。

好的
