### ISSUE TITLE
ENGLISH

### ISSUE THREAD

**Issue by spm81** [hank9999/K5_Tools#13]
hi
it is possible to add ENGLISH?
is there any out there ?

Nice Work

**Comment by hank9999** [comment]
> hi
> it is possible to add ENGLISH?
> is there any out there ?
> 
> Nice Work


Thank for your support. I will add English support recently.

> PS: this tool is designed for losehu chinese firmware, many options are only available for it, such as writing Chinese char table, pinyin char table etc, It may be useless for other firmware.

**Comment by spm81** [comment]
Thanks my friend ...
keep going the good work  
L♡ve it ;)

**Comment by hank9999** [comment]
Finished in #15 and other commits. English translations will appear in v0.7 or dev version in actions.
